# Generated by Django 4.2.3 on 2023-10-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SleepHealth',
            fields=[
                ('person_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('age', models.IntegerField()),
                ('occupation', models.CharField(max_length=100)),
                ('sleep_duration', models.FloatField()),
                ('quality_sleep', models.BooleanField()),
                ('physical_activity_level', models.CharField(max_length=100)),
                ('stress_level', models.IntegerField()),
                ('bmi_category', models.CharField(max_length=50)),
                ('blood_pressure', models.CharField(max_length=50)),
                ('heart_rate', models.IntegerField()),
                ('daily_steps', models.IntegerField()),
                ('sleep_disorder', models.BooleanField()),
            ],
        ),
    ]
