# Generated by Django 4.2.3 on 2023-10-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SleepData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleephealth',
            name='blood_pressure',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sleephealth',
            name='physical_activity_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sleephealth',
            name='quality_sleep',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sleephealth',
            name='sleep_disorder',
            field=models.CharField(max_length=100),
        ),
    ]
