# Generated by Django 4.2.3 on 2023-11-02 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SleepData', '0002_alter_sleephealth_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleephealth',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
